language: node_js
node_js:
  - lts/dubnium
os:
  - linux
dist: bionic
before_install:
  - curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh -o install_nvm.sh
  - bash install_nvm.sh
  - command -v nvm
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install --no-install-recommends yarn
  - nvm install lts/dubnium && nvm use lts/dubnium  && npm install -g yarn
  - yarn compile
cache:
  apt: true
jobs:
  include:
      # Linux
      - stage: build
        name: 'pShare Ubuntu Package'
        script:
          - ./build.linux.sh
      # Windows
      - stage: build
        name: 'pShare Windows Installer'
        install:
          - sudo dpkg --add-architecture i386
          - wget -nc https://dl.winehq.org/wine-builds/winehq.key
          - sudo apt-key add winehq.key
          - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          - sudo apt-get update
          - sudo apt-get install --install-recommends winehq-stable
        script:
          - ./build.win.sh